apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-shop-deployment
  labels:
    app: coffee-shop
spec:
  replicas: 3  # Número de réplicas (pode ajustar conforme necessário)
  selector:
    matchLabels:
      app: coffee-shop
  template:
    metadata:
      labels:
        app: coffee-shop
    spec:
      containers:
        - name: coffee-shop
          image: ${CI_REGISTRY_USER}/coffee-shop:latest  # Nome da imagem Docker
          ports:
            - containerPort: 3000  # Porta em que a aplicação está rodando dentro do container
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: coffee-shop-service
spec:
  type: LoadBalancer  # Tipo de serviço que expõe a aplicação externamente
  ports:
    - port: 80  # Porta externa que será acessível
      targetPort: 3000  # Porta interna que o container usa
  selector:
    app: coffee-shop  # Mapeia para o deployment através de labels
